import React, { Fragment } from 'react'
import { Heading } from 'grommet'
import { Navbar } from '../components/Navbar'

export const Home: React.FC = () => {
  return (
    <Fragment>
      <Heading>Redux + TypeScript</Heading>
      <Navbar />
      <p>
        Hello and welcome! :) This app was generated by the Create React App
        template and bootstrapped with Redux, React Router, TypeScript, ESlint,
        Prettier for you. Take a look around ;)
      </p>
    </Fragment>
  )
}
