import React, { Fragment } from 'react'

export const Home: React.FC = () => {
  return (
    <Fragment>
      <h1>Timesheet app</h1>
      <p>
        Hello and welcome! :) This app was generated by the Create React App
        template and bootstrapped with Redux, React Router, TypeScript, ESlint,
        Prettier for you. Take a look around ;)
      </p>
    </Fragment>
  )
}
