name: React CI/CD

on:
  push:
    branches:

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Build solution
        run: |
          ./generate_env.sh
          echo $FIREBASE_ENV_CONFIG
          cat .env
          yarn --frozen-lockfile
          yarn test:once
          yarn lint
          yarn build
        env:
          FIREBASE_ENV_CONFIG: ${{ secrets.FIREBASE_ENV_CONFIG }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        if: steps.extract_branch.outputs.branch == 'master'
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
