name: React CI/CD

on:
  push:
    branches:

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Extract Branch Name
        run: echo "::set-env name=BRANCH::$(echo ${GITHUB_REF##*/})"
      - name: Build solution
        run: |
          ./env.sh
          yarn --frozen-lockfile
          yarn test:once
          yarn lint
          yarn build
        env:
          FIREBASE_ENV: ${{ secrets.FIREBASE_ENV }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        if: env.BRANCH == 'master'
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
