name: React CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Build solution
        run: |
          ./decrypt_secret.sh
          yarn --frozen-lockfile
          yarn test:once
          yarn lint
          yarn build
        env:
          REACT_ENV: ${{ secrets.REACT_ENV }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
