name: Functions CI/CD

# on:
#   push:
#     branches:
#       - master

on: [push]

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - run: cd functions
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run Tests
        run: yarn test:once
      - run: cd ..
      - run: npm install -g tslint
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
